# Jykell configuration
#markdown: redcarpet
#highlighter: pygments
markdown: kramdown
highlighter: rouge
paginate: 5
language: 'en-uk'

# Website info
name: 'Kamhawi Notes'
description: 'The blog of Mohamed Elkamhawi'

# Author's info
author: 'Mohamed Elkamhawi'
# edit 'categories' in the front matter of every post to match this username
nickname: 'mkamhawi'
bio: 'Passionate about languages since infancy. I speak Arabic, English, French,
and Code.'
location: 'Cairo, Egypt'
url: 'https://kamhawinotes.com/'
image: 'assets/images/profile33.jpg'

short_url: 'https://kamhawinotes.com/'
google_analytics: 'UA-97464899-1'
disqus: 'kamhawi-notes'
twitter: 'mkamhawi'
github: 'mkamhawi'
linkedin: 'mkamhawi'
# edit baseurl to simply '/' if using as your personal page (instead of a project page)
baseurl: '/'

# Permalinks
permalink: /:title
# permalink: /author/:username
# permalink: /tag/:tag


# gems and other configs
plugins: [jekyll-paginate]
exclude: [vendor]

# Additional settings available on the front-matter
# Site logo in the index.html (as in demo.ghost.io)
# Author's page cover in _layouts/author.html
# The same for page.html and tag.html layouts
# Post's page cover as a per-post basis _posts/...
# Disqus comments as a per-post basis
# ...